/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.*;  
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class Ticket_Booking extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs; 
    public Ticket_Booking() {
        initComponents();
        Connect();
        
    }
    public Ticket_Booking(String s,String s1){
        initComponents();
        Connect();
        jLabel21.setText(s1);
        jLabel17.setText(s);
        jScrollPane1.setVisible(false);
        jPanel3.setVisible(false);
        s=jLabel17.getText().trim();
        jLabel21.setVisible(false);
        jLabel1.setVisible(false);
    try{
        String query="Select * from customer;";
        int RecordsFound=0;
        rs=stmt.executeQuery(query);
                    while(rs.next()) {
                if(s.equals(rs.getString("customer_id"))) {
                    RecordsFound++;
                    break;
                }
            }
        if(RecordsFound==1){
         
         jLabel5.setText("Name:-"+rs.getString("name"));
         jLabel6.setText("PassPort ID:- "+rs.getString("passport_id"));
         jLabel7.setText("Gender:- "+rs.getString("gender"));
         jLabel8.setText("DOB:- "+rs.getString("date_of_birth"));
         jLabel9.setText("Phone Number:- "+rs.getString("contact_number"));
         jPanel1.setVisible(true);
        }
        if(RecordsFound==0){
            JOptionPane.showMessageDialog(this,"In-Correct Customer ID","Invalid Input",JOptionPane.ERROR_MESSAGE);
        }
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
        
    }
     public void Connect(){
        try{
       con= DriverManager.getConnection("jdbc:mysql://localhost:3306/airline","root","3308");
       stmt=con.createStatement();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 20, 370, 50);

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 80, 310, 50);

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(400, 30, 240, 40);

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(400, 80, 240, 60);

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 140, 520, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 270, 670, 210);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("Destination");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 60, 150, 40);

        jComboBox2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "USA", "Switzerland", "Canada", "London" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(630, 70, 130, 30);

        jComboBox1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "USA", "Switzerland", "Canada", "London" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 70, 140, 28);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("Origin");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 60, 90, 40);

        jButton1.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 150, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(920, 240, 920, 220);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(790, 370, 70, 30);

        jButton3.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(770, 970, 180, 60);

        jScrollPane1.setBorder(null);

        jTable1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight Id", "Flight Name", "Origin", "Destination", "Departure Time", "Arrival Time", "Date", "Flight Charge", "Available Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(780, 490, 1140, 470);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel4.setText("Customer ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 220, 160, 70);

        jPanel3.setOpaque(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel10.setText("jlabel10");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(160, 50, 190, 50);

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(190, 150, 190, 50);

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel12.setText("jLabel12(From -To)");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 230, 690, 40);

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 340, 640, 50);

        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 400, 240, 40);

        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 290, 260, 40);

        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(150, 90, 140, 70);

        jLabel18.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel18.setText("Flight ID:-");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(20, 50, 130, 40);

        jLabel19.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel19.setText("Flight Name:-");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(20, 160, 160, 40);

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jButton2.setText("Book A Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(530, 460, 190, 60);

        jLabel20.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel20.setText("Seat ID:-");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(20, 100, 120, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 510, 740, 540);

        jLabel17.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 240, 170, 30);

        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1710, 20, 200, 60);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight_selection.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
                String origin = jComboBox1.getSelectedItem().toString().trim();
                String destination = jComboBox2.getSelectedItem().toString().trim(); 
                String sql="select * from flights where(origin='"+origin+"' and destination='"+destination+"');";
                rs=stmt.executeQuery(sql);                
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.setRowCount(0);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("flight_id"),rs.getString("flight_name"),rs.getString("origin"),rs.getString("destination"),rs.getString("departure_time"),rs.getString("arrival_time"),rs.getString("date"),rs.getString("flight_charge"),rs.getString("available_seats")});
            }
            jScrollPane1.setVisible(true);
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTable1.addMouseListener(new MouseAdapter() {
        public void mousePressed(MouseEvent me) {
            JTable table = (JTable) me.getSource();
            Point p = me.getPoint();
            int row = table.rowAtPoint(p);
            if (me.getClickCount() == 2) {
                jLabel10.setText(""+table.getValueAt(row,0));
                jLabel11.setText(""+table.getValueAt(row,1));
                jLabel12.setText("Flight is From "+table.getValueAt(row,2)+" To "+table.getValueAt(row,3));
                jLabel13.setText("Duration is from  "+table.getValueAt(row,4)+" To "+table.getValueAt(row,5));
                jLabel14.setText("Flight Charge:- "+table.getValueAt(row,7)); 
                jLabel15.setText("Date:- "+table.getValueAt(row,6)); 
                int a=Integer.parseInt(table.getValueAt(row,8).toString());
                jLabel1.setText(""+a);
                a=61-a;
                if(a<9)
                jLabel16.setText(""+table.getValueAt(row,0)+"-S0"+a);
                else
                    jLabel16.setText(""+table.getValueAt(row,0)+"-S"+a);
                jPanel3.setVisible(true);
            }
        }
    }); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String flight_id=jLabel10.getText();
        String seat_id=jLabel16.getText();
        String cust_id=jLabel17.getText();
        String Login_id=jLabel21.getText();
        int a=Integer.parseInt(jLabel1.getText());
        try{
            String query="insert into ticket_reservation values('"+seat_id+"','"+flight_id+"','"+cust_id+"','"+Login_id+"');";
            stmt.executeUpdate(query);
            a=a-1;
            JOptionPane.showMessageDialog(this, "Ticket Booked Successfully,Now you will be redirected to Customer Page","Successfull Registration ",JOptionPane.INFORMATION_MESSAGE);
            String query2="update flights set available_seats="+a+" where flight_id='"+flight_id+"';";
            stmt.executeUpdate(query2);
            Customer ob=new Customer(Login_id);
            ob.setSize(1920,1080);
            ob.setVisible(true);
            this.dispose();
            
            
        }
        catch(Exception o){
            JOptionPane.showMessageDialog(this, o);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String cust_id=jLabel17.getText();
        try{
        String sql="delete from customer where customer_id='"+cust_id+"';";
        stmt.executeUpdate(sql);                
        Customer ob=new Customer(jLabel21.getText());
            ob.setSize(1920,1080);
            ob.setVisible(true);
            this.dispose();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
